openapi: 3.0.0
info:
  title: Unified Banking API
  description: API для унифицированного взаимодействия с банковскими сервисами
  version: 1.0.0

servers:
  - url: https://api.example.com/v1
    description: Production server

paths:
  /accounts/{account_id}:
    get:
      summary: Get Account Information
      description: Получение информации о банковском счёте клиента
      parameters:
        - name: account_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Информация о счёте
          content:
            application/json:
              schema:
                type: object
                properties:
                  account_id:
                    type: string
                  account_type:
                    type: string
                  currency:
                    type: string
                  balance:
                    type: number
                    format: float
                  status:
                    type: string
                  created_at:
                    type: string
                    format: date-time
                  customer_id:
                    type: string
  /accounts:
    post:
      summary: Create Account
      description: Создание нового банковского счета
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                customer_id:
                  type: string
                account_type:
                  type: string
                currency:
                  type: string
                initial_deposit:
                  type: number
                  format: float
      responses:
        "201":
          description: Счет успешно создан
          content:
            application/json:
              schema:
                type: object
                properties:
                  account_id:
                    type: string
                  status:
                    type: string
  /payments:
    post:
      summary: Initiate Payment
      description: Инициирование платежа между счетами
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                source_account_id:
                  type: string
                destination_account_id:
                  type: string
                amount:
                  type: number
                  format: float
                currency:
                  type: string
                description:
                  type: string
                schedule_date:
                  type: string
                  format: date-time
      responses:
        "200":
          description: Платеж успешно инициирован
          content:
            application/json:
              schema:
                type: object
                properties:
                  payment_id:
                    type: string
                  status:
                    type: string
                  created_at:
                    type: string
                    format: date-time
  /payments/{payment_id}/status:
    get:
      summary: Get Payment Status
      description: Получение статуса платежа
      parameters:
        - name: payment_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Статус платежа
          content:
            application/json:
              schema:
                type: object
                properties:
                  payment_id:
                    type: string
                  status:
                    type: string
                  completed_at:
                    type: string
                    format: date-time
  /loans/apply:
    post:
      summary: Apply for Loan
      description: Подать заявку на получение кредита
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                customer_id:
                  type: string
                loan_type:
                  type: string
                amount:
                  type: number
                  format: float
                currency:
                  type: string
                term_in_months:
                  type: integer
                annual_income:
                  type: number
                  format: float
                purpose:
                  type: string
      responses:
        "201":
          description: Заявка на кредит успешно создана
          content:
            application/json:
              schema:
                type: object
                properties:
                  loan_application_id:
                    type: string
                  status:
                    type: string
  /loans/{loan_application_id}/status:
    get:
      summary: Get Loan Status
      description: Проверка статуса заявки на кредит
      parameters:
        - name: loan_application_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Статус заявки на кредит
          content:
            application/json:
              schema:
                type: object
                properties:
                  loan_application_id:
                    type: string
                  status:
                    type: string
                  approved_amount:
                    type: number
                    format: float
                  approved_at:
                    type: string
                    format: date-time
  /investments/accounts:
    post:
      summary: Open Investment Account
      description: Открытие инвестиционного счёта
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                customer_id:
                  type: string
                account_type:
                  type: string
                currency:
                  type: string
                initial_investment:
                  type: number
                  format: float
      responses:
        "201":
          description: Инвестиционный счёт успешно создан
          content:
            application/json:
              schema:
                type: object
                properties:
                  investment_account_id:
                    type: string
                  status:
                    type: string
  /customers/{customer_id}:
    get:
      summary: Get Customer Profile
      description: Получение профиля клиента
      parameters:
        - name: customer_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Профиль клиента
          content:
            application/json:
              schema:
                type: object
                properties:
                  customer_id:
                    type: string
                  name:
                    type: string
                  email:
                    type: string
                  phone:
                    type: string
                  address:
                    type: string
                  created_at:
                    type: string
                    format: date-time
    put:
      summary: Update Customer Profile
      description: Обновление профиля клиента
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                phone:
                  type: string
                address:
                  type: string
      responses:
        "200":
          description: Профиль клиента успешно обновлён
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  updated_at:
                    type: string
                    format: date-time

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - BearerAuth: []
